### ISSUE TITLE
Some test cases failing on stable branches (Adapter)

### ISSUE THREAD

**Issue by karntrehan** [samagra-comms/adapter#28]
@chinmoy12c and @pankajjangid05 to list failing tests.

**Comment by chinmoy12c** [comment]
List of failing issues:

`NetcoreServiceTest.sendTextTest()` - Status: Fail
`SunbirdWebPortalAdapterTest.simplePayloadParsing` - Status - Error

**Comment by geeky-abhishek** [comment]
Separate tickets are created and PR is raised for the adapter.  @pankajjangid05 Plz review it
A cleanup ticket is also created.

**Comment by chinmoy12c** [comment]
@pankajjangid05 we need to do a sanity check for netcore whatsapp since some code was changed in classes related to this.
